# DS 3000/CS 3200 Lab 1

Due: Tuesday May 13 in-class

### Submission Instructions
Upload this `ipynb` file to GitHub, and then to Gradescope.  To ensure that your submitted `ipynb` file represents your latest code, make sure to give a fresh `Kernel > Restart & Run All` just before uploading the `ipynb` file to GitHub and verify that the correct version is represented on Gradescope.

### Tips for success
- Collaborate: bounce ideas off of each other, if you are having trouble you can ask your classmates or Dr. Gerber for help with specific issues, however...
- [(See)](http://www.northeastern.edu/osccr/academic-integrity), i.e. you are welcome to **talk about/discuss** (*not* show or allow each other to copy your answers to) the problems.

# Part 1 (40 points): Intro to Markdown

Use the markdown language below to create your own brief wikipedia-esque description of a topic related to International Government and Politics. 

Your mini-wiki page must include:
- three headers: a title, subtitle and subsubtitle (the #, ##, ### syntax)
- an embedded image from a web address (use an [image hosting site](https://makeawebsitehub.com/free-photo-hosting/) if you'd like to upload your own)
- a **markdown** table of size at least 9 cells (i.e. 3 by 3, or 5 by 2)
- a list in **markdown**
- a link to another website

To practice typing in math mode, also include a LaTeX formula describing how your final grade is going to be calculated based on the syllabus, something like:

$$grade = weight_1*score_1 + weight_2*score_2$$

Please be **brief** in your text.  Aim for roughly 3 sentences total of text.

# International Monetary Fund (IMF)
This is a page representing the International Monetary Fund, or IMF
## What is the IMF:
The International Monetary Fund is working towards sustainable growth and long-term propserity for all 191 countries in the organization.
### What does the IMF Do:
The IMF aims to build financial stability by offering policy advice, financial assistance, and capacity development.
![alt text](https://www.google.com/url?sa=i&url=https%3A%2F%2Fepthinktank.eu%2F2015%2F10%2F15%2Fthe-international-monetary-fund-imf-rebalancing-global-economic-weights%2F&psig=AOvVaw2tEz5IRU2s3OHbx5RQUNlR&ust=1747216225624000&source=images&cd=vfe&opi=89978449&ved=0CBUQjRxqFwoTCODHoeaVoI0DFQAAAAAdAAAAABAE)


| 2  |  6 |  2 |  3 |  4 |
|----|----|----|----|----|
| 5  |  7 |  4 |  0 |  3 |
| 2  |  5 |  8 |  7 |  2 |
| 8  |  3 |  1 |  5 |  7 |

<ol>
    <li>International Monetary Fund</li>
    <li>The three ways to build financial stability are focused on.</li>
    <li>The IMF has 191 members total!</li>
</ol>

To learn more about the IMF's history and evolution, pleas visit [https://www.britannica.com/topic/International-Monetary-Fund]

# Part 2: Numpy
## Part 2.1: Creating Arrays (10 points)

Create the following two arrays using the NumPy library and then print them out. Call the first array `array_a` and the second array `array_b` (make sure you keep the `import` statement below):

$$\mathbf{array_a} = \begin{bmatrix}3 & 8 & -2 & 3\\
.5 & -1 & 6 & 4\\
-5 & 7 & -42 & 2
\end{bmatrix}$$

$$\mathbf{array_b} = \begin{bmatrix}42 & 38 & 34\\
30 & 26 & 22\\
18 & 14 & 10\\
6 & 2 & -2\\
-6 & -10 & -14
\end{bmatrix}$$

In [13]:
# make sure to import numpy library
import numpy as np

In [14]:
array_a = np.array([[3, 8, -2, 3],
                    [.5, -1, 6, 4],
                    [-5, 7, -42, 2]])
array_b = np.array([[42, 38, 24],
                    [30, 26, 22],
                     [18, 14, 10],
                    [6, 2, -2],
                    [-6, -10, -14]])

In [15]:
# uncomment below to print array_a
array_a

array([[  3. ,   8. ,  -2. ,   3. ],
       [  0.5,  -1. ,   6. ,   4. ],
       [ -5. ,   7. , -42. ,   2. ]])

In [16]:
# uncomment below to print array_b
array_b

array([[ 42,  38,  24],
       [ 30,  26,  22],
       [ 18,  14,  10],
       [  6,   2,  -2],
       [ -6, -10, -14]])

## Part 2.2: Exploring Arrays (15 points)

1. Give the shape, size, ndim, and nbytes for each of the two arrays.
1. Take the transpose of both arrays. Call these `t_array_a` and `t_array_b`.
1. Try to add `array_a` and `t_array_b` (*prove* and *show* you did this with commented out code), then remove the last column of `t_array_b` and try to add them again. In a markdown cell, explain what happened.

In [17]:
# Array A shape
shape_a = array_a.shape
# Array A size
size_a = array_a.size
# Array A ndim
ndim_a = array_a.ndim
# Array A nbytes
nbytes_a = array_a.nbytes
print("Array A:")
print(f'Shape: {shape_a}')
print(f'Size: {size_a}')
print(f'Ndim: {ndim_a}')
print(f'Nbytes: {nbytes_a}')
print()
# Array B shape
shape_b = array_b.shape
# Array B size
size_b = array_b.size
# Array B ndim
ndim_b = array_b.ndim
# Array B nbytes()
nbytes_b = array_b.nbytes

print("Array B:")
print(f'Shape: {shape_b}')
print(f'Size: {size_b}')
print(f'Ndim: {ndim_b}')
print(f'Nbytes: {nbytes_b}')

# Transposing both arrays
t_array_a = array_a.T
t_array_b = array_b.T

t_array_b_remove = t_array_b[:, :-1]

add_arrays = array_a + t_array_b_remove

print(add_arrays)

Array A:
Shape: (3, 4)
Size: 12
Ndim: 2
Nbytes: 96

Array B:
Shape: (5, 3)
Size: 15
Ndim: 2
Nbytes: 120
[[ 45.   38.   16.    9. ]
 [ 38.5  25.   20.    6. ]
 [ 19.   29.  -32.    0. ]]

# Explanation:
After trying to add array_a and t_array_b, although the code adds them together seemingly correctly in the output, in reality it should be returning a ValueError. By removing one column of the array, the shapes for both arrays are now different. t_array_b now has a shape that differs by one column to array_a, meaning that NumPy cannot successfully add arrays of different shapes when performing mathematical operations.

# Part 3: Pandas
## Part 3.1: Reading in Data (5 points)

On Canvas is the `train_stations_europe.csv` file. It was adapted from [this Kaggle data set](https://www.kaggle.com/datasets/headsortails/train-stations-in-europe). Read this data set in, using the `id` as the index column, and print the first few rows of the data. Make sure you keep the `import` statement below!

In [18]:
# make sure to import pandas library
import pandas as pd

In [19]:
train_data_df = pd.read_csv("train_stations_europe.csv", index_col = 'id')
train_data_df

,name,latitude,longitude,parent_station_id,country,time_zone,is_city,is_main_station,is_airport
id,,,,,,,,,
1,Chateau-Arnoux-St-Auban,44.081790,6.001625,NaN,FR,Europe/Paris,True,False,False
2,Chateau-Arnoux-St-Auban,44.061565,5.997373,1.0,FR,Europe/Paris,False,True,False
3,Chateau-Arnoux Mairie,44.063863,6.011248,1.0,FR,Europe/Paris,False,False,False
4,Digne-les-Bains,44.350000,6.350000,NaN,FR,Europe/Paris,True,False,False
6,Digne-les-Bains,44.088710,6.222982,4.0,FR,Europe/Paris,False,True,False
...,...,...,...,...,...,...,...,...,...
68175,Bari Villaggio del Lavoratore,41.104234,16.822596,NaN,IT,Europe/Rome,False,False,False
68176,Baucca-Garavelle,43.442030,12.250215,NaN,IT,Europe/Rome,False,False,False
68177,Bibbiano Fossa,44.674312,10.478726,NaN,IT,Europe/Rome,False,False,False
68178,Bibbiano Via Monti,44.661871,10.466608,NaN,IT,Europe/Rome,False,False,False
68179,Bivio Barco,44.694544,10.498249,NaN,IT,Europe/Rome,False,False,False

## Part 3.2: Manipulating Data (20 points)

1. Create a subset of the data set which (a) **includes** only train stations in Belgium and (b) **excludes** all train stations which are **not** in a city. Make sure to save this subset as a new data frame and print the first few rows of the data.
1. Use the `.describe()` function to produce summary statistics for the subset from the previous part. Create a markdown cell and explain:    - What Series did the `.describe()` function run on? What Series did it not run on? What is the difference, and what does this mean the `.describe()` function is used for?

In [20]:
# Part 3.2 (a)
belgium_stations = train_data_df[train_data_df['country'] == 'BE']

# Part 3.2 (b)
belgium_stations = belgium_stations[belgium_stations['is_city'] == True]
belgium_stations
belgium_stations.describe()

        latitude  longitude  parent_station_id
count   9.000000   9.000000                0.0
mean   50.719715   4.810847                NaN
std     0.366820   0.996916                NaN
min    49.999779   3.263740                NaN
25%    50.617431   4.351739                NaN
50%    50.718089   4.444643                NaN
75%    50.979756   5.701847                NaN
max    51.221722   6.120155                NaN

# Part 3.2 (b)
The .describe() function only runs on Numeric Series, meaning it only takes into consideration columns like "latitude" and "longitude", and does not run on columns like "name", "country", or "time_zone". This implies that .describe() can be used for further calculations for numeric data indicators, like the mean, total count, or standard deviation.

# Part 4: GitHub (10 points)

When you finish the first three parts, give one last restart and run all to this file. Then, go to the [DS 3000 GitHub](https://github.com/eaegerber/ds3000_summer25), fork it and then clone it to your local machine. Then:

- In the forked and cloned ds3000_summer25 repo, make a new branch (`git checkout -b lab-upload`)
- Create a folder with your name (as Dr. Gerber did)
- Navigate to that folder and place this jupyter notebook inside
- Add the file as the change to be committed (`git add .\Lab1_MyName.ipynb`)
- Check `git status`, your changes should be staged
- Commit the changes with a short message (`git commit -m "My message"`)
- Push the repository to GitHub (`git push origin lab-upload`)
- Navigate the the GitHub in the browser and create a pull request
- Once the pull request is merged, you can delete your branch in the "Pull Requests" tab in the browser
- Finally, upload the Lab to Gradescope. When you do so, it will give you the option to do it via GitHub; do that.